services:

  web-app:
    build: .
    image: django-test:0.1
    restart: always
    command: gunicorn -w 2 -b 0.0.0.0:8000 DjangoProjectCeleryTest.wsgi:application;
    environment:
      CELERY_BROKER_URL: amqp://admin:admin@broker:5672/
      CELERY_RESULT_BACKEND: redis://cache:6379/
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3

  celery-worker:
    image: django-test:0.1
    restart: always
    command: celery -A DjangoProjectCeleryTest.celery:celery worker -l info -Q celery
    environment:
      CELERY_BROKER_URL: amqp://admin:admin@broker:5672/
      CELERY_RESULT_BACKEND: redis://cache:6379/
    volumes:
      - ./db.sqlite3:/app/db.sqlite3

  celery-beat:
    image: django-test:0.1
    restart: always
    command: celery -A DjangoProjectCeleryTest.celery:celery beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      CELERY_BROKER_URL: amqp://admin:admin@broker:5672/
      CELERY_RESULT_BACKEND: redis://cache:6379/
    volumes:
      - ./db.sqlite3:/app/db.sqlite3

  broker:
    image: rabbitmq:3.13.6-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15672:15672"
    volumes:
      - "./rabbitmq:/var/lib/rabbitmq"

  cache:
    image: redis:7.2.4-alpine
    restart: always
